export const COMMENT_STORE_REQUEST = "COMMENT_STORE_REQUEST"
export const COMMENT_STORE_SUCCESS = "COMMENT_STORE_SUCCESS"
export const COMMENT_STORE_RESET = "COMMENT_STORE_RESET"

export const COMMENT_INDEX_REQUEST = "COMMENT_INDEX_REQUEST"
export const COMMENT_INDEX_SUCCESS = "COMMENT_INDEX_SUCCESS" 
