export const POST_STORE_REQUEST = "POST_STORE_REQUEST"
export const POST_STORE_SUCCESS = "POST_STORE_SUCCESS"
export const POST_STORE_FAIL = "POST_STORE_FAIL"
export const POST_STORE_RESET = "POST_STORE_RESET"

export const POST_SHOW_REQUEST = "POST_SHOW_REQUEST"
export const POST_SHOW_SUCCESS = "POST_SHOW_SUCCESS"
export const POST_SHOW_FAIL = "POST_SHOW_FAIL"

export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POST_LIKE_RESET = "POST_LIKE_RESET"
export const POST_LIKE_INDEX = "POST_LIKE_INDEX"
export const POST_LIKE_INDEX_RESET = "POST_LIKE_INDEX_RESET"

export const POST_INDEX_SUCCESS = "POST_INDEX_SUCCESS"
export const POST_INDEX_REQUEST = "POST_INDEX_REQUEST"
