export const PROFILE_INDEX_REQUEST = 'PROFILE_INDEX_REQUEST'
export const PROFILE_INDEX_SUCCESS = 'PROFILE_INDEX_SUCCESS'
export const PROFILE_INDEX_FAIL = 'PROFILE_INDEX_FAIL'
// export const PROFILE_INDEX_REQUEST = 'PROFILE_INDEX_REQUEST'

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'

export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST'
export const PROFILE_EDIT_FAIL = 'PROFILE_EDIT_FAIL'
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS'

export const PROFILE_SEARCH_REQUEST = "PROFILE_SEARCH_REQUEST"
export const PROFILE_SEARCH_SUCCESS = "PROFILE_SEARCH_SUCCESS"
export const PROFILE_SEARCH_RESET = "PROFILE_SEARCH_RESEt"